services:
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM ruby:3.2.2-slim-bullseye
        WORKDIR /app
        COPY Gemfile Gemfile.lock /app/
        RUN apt-get update && apt-get install -y \
                build-essential sshpass \
            && \
            gem install bundler --no-document && \
            bundle install && \
            apt-get remove --autoremove --purge -y \
                build-essential \
            && \
            apt-get clean && \
            rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
        COPY entrypoint.thor /app/
        ENTRYPOINT ["/app/entrypoint.thor"]
        CMD []
    depends_on:
      - googlecloud
    volumes:
      - .:/app
  googlecloud:
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/x86_64 gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
        WORKDIR /uploads
        RUN apt-get update && apt-get install -y \
                openssh-server \
            && \
            mkdir /var/run/sshd && \
            echo "root:secret" | chpasswd && \
            sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config
        EXPOSE 22
        CMD ["/usr/sbin/sshd", "-D"]
    volumes:
      - .:/app
